name: Rapport de bug
description: Utilisez ce template pour signaler un bug.
title: '[Bug]: '
labels: ['bug']
projects: ['Natchii59/2']

body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir ce template pour nous aider à reproduire et réparer le bug plus rapidement.

  - type: textarea
    attributes:
      label: Description
      description: Décrivez le bug en détail. (Requis)
      placeholder: Décrivez le bug ici...

  - type: textarea
    attributes:
      label: Étapes pour reproduire
      description: Fournissez les étapes nécessaires pour reproduire le bug. (Requis)
      placeholder: |
        1. Remplir cette query '...'
        2. Mettre ces paramètres '...'
        3. Exécuter la query
        4. Voir l'erreur

  - type: textarea
    attributes:
      label: Comportement attendu
      description: Décrivez ce que vous vous attendiez à voir. (Requis)
      placeholder: Comportement attendu...

  - type: textarea
    attributes:
      label: Comportement actuel
      description: Décrivez ce que vous voyez actuellement. (Requis)
      placeholder: Comportement actuel...

  - type: textarea
    attributes:
      label: Logs
      description: Ajoutez les logs pertinents pour aider à diagnostiquer le problème.
      placeholder: Logs...
      render: shell

  - type: dropdown
    attributes:
      label: Sévérité
      description: Sélectionnez le niveau de sévérité du bug. (Requis)
      options:
        - Très faible
        - Faible
        - Moyenne
        - Élevée
        - Critique

  - type: textarea
    attributes:
      label: Autres considérations
      description: Mentionnez d'autres aspects importants à prendre en compte.
      placeholder: Autres considérations importantes...
