blank_issues_enabled: true
contact_links:
  - name: Voir la documentation du workflow
    url: https://github.com/Natchii59/ozepi/blob/master/docs/WORKFLOW.md
    about: En savoir plus sur notre processus de workflow.
