name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Test
        run: pnpm lint
